#!/bin/bash

source /n/app/conda2/etc/profile.d/conda.sh
conda activate mutts

CDTS_female="/n/scratch3/users/a/ak586/output/sex-specific/CDTS/female/split/genome_CDTS.bed"
CDTS_male="/n/scratch3/users/a/ak586/output/sex-specific/CDTS/male/split/genome_CDTS.bed"

sort-bed <(awk -v OFS='\t' '{print $1,$2,$3,$6,"FEMALE"}' $CDTS_female) <(awk -v OFS='\t' '{print $1,$2,$3,$6,"MALE"}' $CDTS_male) | python calc_diff.py > "/n/scratch3/users/a/ak586/output/sex-specific/CDTS_sexdiff.bed"

sort -k4,4n "/n/scratch3/users/a/ak586/output/sex-specific/CDTS_sexdiff.bed"
